Source/VrseWebApplication/Models/Data01Model.cs
namespace VrseWebApplication.Models;

public sealed class Data01Model
{
    public int id { get; set; }
    public string? name { get; set; }
}

Source/VrseWebApplication/Models/DxTestPartial01ViewModel.cs
namespace VrseWebApplication.Models;

public sealed class DxTestPartial01ViewModel
{
    public int Id { get; set; }
}

Source/VrseWebApplication/Models/DxTestPartial03ViewModel.cs
namespace VrseWebApplication.Models;

using System.ComponentModel.DataAnnotations;

public sealed class DxTestPartial03ViewModel
{
    [Required, Range(1, 1000)]  public int Id { get; set; }
}

Source/VrseWebApplication/Models/ErrorViewModel.cs
namespace VrseWebApplication.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Source/VrseWebApplication/Models/TestModalDataViewModel.cs
namespace VrseWebApplication.Models;

public sealed class TestModalDataViewModel
{
    public int Id { get; set; }
    public string? Name { get; set; }
}

Source/VrseWebApplication/Models/TestPartial03ViewModel.cs
namespace VrseWebApplication.Models;

public sealed class TestPartial03ViewModel
{
    public int Id { get; set; }
}

Source/VrseWebApplication/Controllers/DataController.cs
namespace VrseWebApplication.Controllers;

using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Models;

public sealed class DataController : Controller
{
    public IActionResult LoadAllData01(DataSourceLoadOptions loadOptions)
    {
        var all = new List<Data01Model>
        {
            new()
            {
                id = 1,
                name = "Anton"
            },
            new()
            {
                id = 2,
                name = "Berta"
            },
            new()
            {
                id = 3,
                name = "Cäsar"
            },
            new()
            {
                id = 4,
                name = "Dora"
            },
        };

        return Json(DataSourceLoader.Load(all, loadOptions));
    }
}

Source/VrseWebApplication/Controllers/HomeController.cs
namespace VrseWebApplication.Controllers;

using Models;

public class HomeController : Controller
{
    private readonly ILogger _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Source/VrseWebApplication/Controllers/TestController.cs
namespace VrseWebApplication.Controllers;

using Code;
using Models;

public sealed class TestController : Controller
{
    private readonly ILogger _logger;
    private readonly IViewRenderService _viewRenderer;

    public TestController(
        ILogger<TestController> logger,
        IViewRenderService viewRenderer)
    {
        _logger = logger;
        _viewRenderer = viewRenderer;
    }

    [HttpGet]
    public IActionResult Test01()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Test02()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> GetPartialView01(int id)
    {
        return Json(
            new
            {
                html = await _viewRenderer.RenderPartialView(this, @"Partials/PartialView01", id, ViewData)
            });
    }

    [HttpPost]
    public async Task<IActionResult> GetPartialView02(int id)
    {
        return Json(
            new
            {
                html = await _viewRenderer.RenderPartialView(this, @"Partials/PartialView02", id, ViewData)
            });
    }

    [HttpPost]
    public async Task<IActionResult> GetPartialView03(int id)
    {
        return Json(
            new
            {
                html = await _viewRenderer.RenderPartialView(this, @"Partials/PartialView03",
                    new TestPartial03ViewModel { Id = id }, ViewData)
            });
    }

    [HttpPost]
    public async Task<IActionResult> PostPartialView03(TestPartial03ViewModel model)
    {
        if (model.Id <= 0)
        {
            ModelState.AddModelError(string.Empty, "Value must be greater than zero.");
        }

        if (!ModelState.IsValid)
        {
            return Json(
                new
                {
                    error = true,
                    html = await _viewRenderer.RenderPartialView(this, @"Partials/PartialView03", model, ViewData)
                });
        }

        return Json(
            new
            {
                html = await _viewRenderer.RenderPartialView(this, @"Partials/PartialView04", model.Id, ViewData)
            });
    }
}

Source/VrseWebApplication/Controllers/TestDevExtremeController.cs
namespace VrseWebApplication.Controllers;

using Code;
using Models;

public sealed class TestDevExtremeController : Controller
{
    private readonly ILogger _logger;
    private readonly IViewRenderService _viewRenderer;

    public TestDevExtremeController(
        ILogger<TestDevExtremeController> logger,
        IViewRenderService viewRenderer)
    {
        _logger = logger;
        _viewRenderer = viewRenderer;
    }

    [HttpGet]
    public IActionResult DxTest01()
    {
        return View();
    }

    [HttpGet]
    public IActionResult DxTest02()
    {
        return View();
    }

    [HttpGet]
    public IActionResult DxTest03()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> GetPartialView01(int id)
    {
        return Json(
            new
            {
                html = await _viewRenderer.RenderPartialView(this, @"Partials/DxPartialView01",
                    new DxTestPartial01ViewModel { Id = id }, ViewData)
            });
    }

    [HttpPost]
    public async Task<IActionResult> GetPartialView03(int id)
    {
        return Json(
            new
            {
                html = await _viewRenderer.RenderPartialView(this, @"Partials/DxPartialView03",
                    new DxTestPartial03ViewModel { Id = id }, ViewData)
            });
    }

    [HttpPost]
    public async Task<IActionResult> DxPostPartialView01(DxTestPartial01ViewModel model)
    {
        if (model.Id <= 0)
        {
            ModelState.AddModelError(string.Empty, "Value must be greater than zero.");
        }

        if (!ModelState.IsValid)
        {
            return Json(
                new
                {
                    error = true,
                    html = await _viewRenderer.RenderPartialView(this, @"Partials/DxPartialView01", model, ViewData)
                });
        }

        return Json(
            new
            {
                html = await _viewRenderer.RenderPartialView(this, @"Partials/DxPartialView02", model.Id, ViewData)
            });
    }

    [HttpPost]
    public async Task<IActionResult> DxPostPartialView03(DxTestPartial03ViewModel model)
    {
        if (model.Id <= 0)
        {
            ModelState.AddModelError(string.Empty, "Value must be greater than zero.");
        }

        if (!ModelState.IsValid)
        {
            return Json(
                new
                {
                    error = true,
                    successful = false,
                    html = await _viewRenderer.RenderPartialView(this, @"Partials/DxPartialView03", model, ViewData)
                });
        }

        return Json(
            new
            {
                error = false,
                successful = true,
                message = $"Received ID {model.Id}",
                id = model.Id
            });
    }

    [HttpPost]
    public async Task<IActionResult> DxPostView03(DxTestPartial03ViewModel model)
    {
        await Task.CompletedTask;

        if (model.Id <= 0)
        {
            ModelState.AddModelError(string.Empty, "Value must be greater than zero.");
        }

        if (!ModelState.IsValid)
        {
            var allErrors = ModelState.Values.SelectMany(v => v.Errors);

            return Json(
                new
                {
                    error = true,
                    successful = false,
                    message = string.Join(@"<br/>", allErrors.Select(e => e.ErrorMessage))
                });
        }

        return Json(
            new
            {
                error = false,
                successful = true,
                message = $"Received ID {model.Id}",
                id = model.Id
            });
    }
}

Source/VrseWebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Tests";
}

<div>
	<h2>Tests</h2>
	
	<div class="row mt-3">
		<div class="col-sm-12 col-md-6">
			<div class="list-group">
				<a class="list-group-item list-group-item-action" asp-controller="Test" asp-action="Test01">Test 01 &ndash; Multiple nested AJAX calls</a>
				<a class="list-group-item list-group-item-action" asp-controller="Test" asp-action="Test02">Test 02 &ndash; AJAX calls to AJAX form</a>
			</div>
		</div>
	</div>
	
	<h4 class="mt-5">DevExtreme Tests</h4>
	
	<div class="row mt-3">
		<div class="col-sm-12 col-md-6">
			<div class="list-group">
				<a class="list-group-item list-group-item-action" asp-controller="TestDevExtreme" asp-action="DxTest01">DevExtreme Test 01 &ndash; AJAX calls to DX AJAX form</a>
				<a class="list-group-item list-group-item-action" asp-controller="TestDevExtreme" asp-action="DxTest02">DevExtreme Test 02 &ndash; Bootstrap Modal</a>
				<a class="list-group-item list-group-item-action" asp-controller="TestDevExtreme" asp-action="DxTest03">DevExtreme Test 02 &ndash; Most simple Bootstrap Modal</a>
			</div>
		</div>
	</div>

	<div class="row mt-5">
		<div class="col-12">
			<p>In the above tests, please also see the Browser's JavaScript console for additional logging information of the tests.</p>
		</div>
	</div>
</div>

Source/VrseWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] – View Render Service Example</title>
	
	<link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico">

	<link rel="stylesheet" href="~/css/dx.light.css" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/VrseWebApplication.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" asp-append-version="true" />

	<script src="~/lib/darkreader/darkreader.js"></script>
	<script src="~/lib/sweetalert2/sweetalert2.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
	<script src="~/lib/devextreme/js/dx.all.js"></script>
	<script src="~/lib/devextreme/js/dx.aspnet.mvc.js"></script>
	<script src="~/lib/devextreme/js/dx.aspnet.data.js"></script>
	<script src="~/lib/devextreme/js/localization/dx.messages.de.js"></script>

	<script>
		DarkReader.setFetchMethod(window.fetch);

		// Enable when the system color scheme is dark.
		DarkReader.auto({
			brightness: 100,
			contrast: 90,
			sepia: 10
		});
	</script>

	<script>
		var loadingPanelClosed = true;

		function handleError(message) {
			console.error(message);
			if (!!message) {
					// https://sweetalert2.github.io/#configuration
					Swal.fire({
						title: "Something went wrong",
						html: message,
						showCancelButton: true,
						cancelButtonText: "Close",
						focusCancel: true,
						showConfirmButton: false,
						heightAuto: false,
						allowEscapeKey: true,
						allowEnterKey: true
					});
			}
		}

		function handleSuccess(message) {
			console.log(message);
			if (!!message) {
					// https://sweetalert2.github.io/#configuration
					Swal.fire({
						title: "Success",
						html: message,
						showCancelButton: true,
						cancelButtonText: "Close",
						focusCancel: true,
						showConfirmButton: false,
						heightAuto: false,
						allowEscapeKey: true,
						allowEnterKey: true
					});
			}
		}

		function showLoadingPanel($container, delay) {
			if (delay === void 0) {
				delay = 500;
			}
			loadingPanelClosed = false;
			setTimeout(function() {
					if (!loadingPanelClosed) {
						const $loadingPanel = $("#loading-panel");
						const pos = $container.position() || { top: 0, left: 0 };
						let height = $container.outerHeight(true);
						if (height === 0) {
							$container.css("min-height", "150px");
							height = 150;
						}
						$loadingPanel.css("top", pos.top + "px");
						$loadingPanel.css("left", pos.left + "px");
						$loadingPanel.width($container.outerWidth(true));
						$loadingPanel.height(height);
						$loadingPanel.addClass("show");
					}
				},
				delay);
		}

		function hideLoadingPanel() {
			loadingPanelClosed = true;
			const $loadingPanel = $("#loading-panel");
			$loadingPanel.removeClass("show");
			$loadingPanel.css("top", 0);
			$loadingPanel.css("left", 0);
			$loadingPanel.width(0);
			$loadingPanel.height(0);
		}

		function sleep(milliseconds) {
			const now = new Date().getTime();
			while (new Date().getTime() < now + milliseconds) {
				/* Do nothing */
			}
		};

		function renderFormGroupsInContainer($container) {
			//Client-Validation
			if ($.validator !== undefined && $.validator.unobtrusive !== undefined) {
				$.validator.unobtrusive.parse($container);
			}
			//Bootstrap - Popover initialisieren
			$("[data-toggle='popover']").popover();
		}

		function fillHtmlIntoContainer(html, $container) {
			$container.html(html);
			renderFormGroupsInContainer($container);
		}
	</script>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">View Render Service Examples</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
					<ul class="navbar-nav">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" href="https://github.com/UweKeim/example-net-core-rendered-views-ajax">GitHub project</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
<div class="container">
	<main role="main" class="pb-3 pt-4">
		@RenderBody()
	</main>
</div>

<div id="loading-panel">
	<div class="loading-panel-inner">
		<div class="loading-panel-overlay"></div>
			<img src="~/images/loading.svg" alt="" asp-append-version="true"/>
		<div class="loading-panel-text">Loading…</div>
	</div>
</div>

<footer class="border-top footer text-muted mt-5 mb-2">
		<div class="container mt-2">
			<a asp-controller="Home" asp-action="Index">Home</a>
			&nbsp;
			<a href="https://github.com/UweKeim/example-net-core-rendered-views-ajax">GitHub project</a>
		</div>
	</footer>

	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Source/VrseWebApplication/Views/Test/Partials/PartialView03.cshtml
@model VrseWebApplication.Models.TestPartial03ViewModel

<script>
	function PartialView03Func1(a) {
		console.log(`Partial View 03: PartialView03Func1('${a}').`);
	}

	$(function() {
		console.log("Partial View 03: Document ready.");
		PartialView03Func1("p3");
		View02Func1("p3");
	});

	function sendForm_begin() {
		console.log("Partial View 03: sendForm_begin.");

		showLoadingPanel($('body'), 1);
		sleep(1000);
	}

	function sendForm_complete() {
		console.log("Partial View 03: sendForm_complete.");

		sleep(1000);
		hideLoadingPanel();
	}

	function sendForm_success(data) {
		console.log("Partial View 03: sendForm_success.");

		sleep(1000);
		hideLoadingPanel();

		if (data.error) {
			// Im Fehlerfall, Partial in meinem Container anzeigen.
			const cont = $('#partial-view-03-container');
			fillHtmlIntoContainer(data.html, cont);
		} else {
			// Erfolg, Partial in anderem Container anzeigen.
			const cont = $('#partial-view-04-container');
			fillHtmlIntoContainer(data.html, cont);
		}
	}
</script>

<h3>Partial View 03</h3>

<p>Content of the Partial View 03. Passed ID: <strong>@Model?.Id</strong>.</p>

@* https://dotnetthoughts.net/jquery-unobtrusive-ajax-helpers-in-aspnet-core/ *@
<form id="formPartial03"
      asp-antiforgery="true"
      asp-controller="Test"
      asp-action="PostPartialView03"
      data-ajax="true"
      data-ajax-method="post"
      data-ajax-begin="sendForm_begin"
      data-ajax-complete="sendForm_complete"
      data-ajax-success="sendForm_success"
      data-ajax-failure="sendForm_failure"
      autocomplete="off">
	
	@Html.ValidationSummary()

	<div class="form-panel">
		<div class="form-fields-area">
			<div class="row">
				<div class="col-12">
					@Html.LabelFor(m => m.Id, new { @class = @"form-label" })
				</div>
				<div class="col-12">
					@Html.TextBoxFor(m => m.Id, new { @class = @"form-control w-100" })
					@Html.ValidationMessageFor(m => m.Id)
				</div>
			</div>

			<div class="form-button-area">
				<hr/>
				<div class="row">
					<div class="col-12">
						<button type="submit" class="btn btn-primary">Send</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

<div id="partial-view-04-container" class="mt-3">
	Click <kbd>Send</kbd>.
</div>

Source/VrseWebApplication/Views/TestDevExtreme/DxTest03.cshtml
@using VrseWebApplication.Controllers
@using VrseWebApplication.Models
@using VrseWebApplication.Code
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model VrseWebApplication.Models.DxTestPartial03ViewModel

@{
	ViewData[@"Title"] = "DX Test 03 – Most simple Bootstrap Modal";
}

@section Scripts {
	<script>
		// --------------------------------

		$(function() {
			console.log("DX Test 03: Document ready.");

			const $dd = $("#idSelectControl");
			if ($dd) {
				// Das machen, um einen ggf. schon gefüllten Wert auszuwählen.
				const dd = $dd.dxDropDownBox('instance');
				if (dd) dd._createPopup();
			}

			//DevExpress.ui.dxOverlay.baseZIndex(2000);
		});

		// --------------------------------
		// Modal.

		var didEverShowSendPopup = false;

		function getSendModalInstance() {
			const c = document.getElementById('sendModal');
			return bootstrap.Modal.getOrCreateInstance(c);
		}

		function showSendModal() {
			didEverShowSendPopup = true;
			getSendModalInstance().show();
		}

		function hideSendModal() {
			getSendModalInstance().hide();
			hideLoadingPanel();
		}

		// --------------------------------
		// AJAX form.

		function sendForm_begin() {
			console.log("DX View 03: sendForm_begin.");

			showLoadingPanel($('body'), 1);
		}

		function sendForm_complete() {
			console.log("DX View 03: sendForm_complete.");
			hideLoadingPanel();
		}

		function sendForm_success(data) {
			console.log("DX View 03: sendForm_success.");

			hideSendModal();

			if (data.error) {
				handleError(data.message);
			} else {
				hideSendModal();
				handleSuccess(data.message);
			}
		}

		function sendForm_failure(data) {
			console.log("DX View 03: sendForm_failure.");
		}

		function DxView01Func1(a) {
			console.log(`DX View 01: DxView01Func1('${a}').`);
		}

		// ---------------------------
		// Fetch modal form content and show modal.

		function startShowSendModal() {
			showSendModal();
		}

		function idSelect_valueChanged(e) {
			const $dataGrid = $("#embedded-idselect-grid");

			if ($dataGrid.length) {
				const dataGrid = $dataGrid.dxDataGrid("instance");
				dataGrid.selectRows(e.value, false);
			}
		}

		function idSelect_displayExpr(item) {
			return item && `${item.@nameof(Data01Model.name)}`;
		}
	</script>
}

<h2>@ViewData[@"Title"]</h2>

<div class="row mt-4">
	<div class="col-12">
		<a href="javascript:void(0)" class="btn btn-primary" onclick="startShowSendModal()">Show modal</a>
	</div>
</div>

@* https://dotnetthoughts.net/jquery-unobtrusive-ajax-helpers-in-aspnet-core/ *@
<form id="sendModalForm"
      asp-antiforgery="true"
      asp-controller="TestDevExtreme"
      asp-action="DxPostView03"
      data-ajax="true"
      data-ajax-method="post"
      data-ajax-begin="sendForm_begin"
      data-ajax-complete="sendForm_complete"
      data-ajax-success="sendForm_success"
      data-ajax-failure="sendForm_failure"
      autocomplete="off">

	<div class="modal fade" data-bs-backdrop="static" id="sendModal" name="sendModal" tabindex="-1" aria-labelledby="sendModalTitle" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="sendModalTitle">DX Test Modal</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
				</div>

				<div class="modal-body mb-3" id="sendModalBody">
					@using (Html.DevExtreme().ValidationGroup())
					{
						@Html.ValidationSummary()

						<div class="form-panel">
							<div class="form-fields-area">
								<div class="row">
									<div class="col-12">
										@Html.LabelFor(m => m.Id, new { @class = @"form-label" })
									</div>
									<div class="col-12">
										<div class="d-flex">
											<div class="flex-grow-1">
												@* https://demos.devexpress.com/ASPNetCore/Demo/DropDownBox/SingleSelection/ *@
												@(Html.DevExtreme().DropDownBoxFor(m => m.Id)
													//.DeferRendering(false)
													.DropDownOptions(o => o.Height(350).Container(@"#sendModal")) // Notwendig wenn in Modal. https://supportcenter.devexpress.com/ticket/details/t678794
													.ID(@"idSelectControl")
													.ValueExpr(nameof(Data01Model.id))
													.DisplayExpr(new JS(@"idSelect_displayExpr"))
													.ElementAttr(@"data-grid", @"embedded-idselect-grid")
													.DataSource(d => d.Mvc()
														.Controller(nameof(DataController).Cn())
														.LoadAction(nameof(DataController.LoadAllData01))
														.LoadMode(DataSourceLoadMode.Raw)
														.Key(nameof(Data01Model.id)))
													.Placeholder("Select data")
													.OnValueChanged(@"idSelect_valueChanged")
													.ContentTemplate(new TemplateName(@"EmbeddedIdSelect")))
												@Html.ValidationMessageFor(m => m.Id)
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					}
				</div>

				<div class="modal-footer">
					<button type="submit" class="btn btn-primary">Send</button>
					<button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
				</div>
			</div>
		</div>
	</div>
</form>

@using (Html.DevExtreme().NamedTemplate(@"EmbeddedIdSelect"))
{
	@(Html.DevExtreme().DataGrid()
		.ID(@"embedded-idselect-grid")
		.DataSource(new JS(@"component.getDataSource()"))
		.Columns(columns =>
		{
			columns.Add().DataField(nameof(Data01Model.id)).Caption("ID").Visible(false);
			columns.Add().DataField(nameof(Data01Model.name)).Caption("Name");
		})
		.HoverStateEnabled(true)
		.Paging(p => p.PageSize(10))
		.SearchPanel(sp => sp.Visible(true))
		.FilterRow(f => f.Visible(true))
		.Scrolling(s => s.Mode(GridScrollingMode.Virtual))
		.Height(345)
		.Selection(s => s.Mode(SelectionMode.Single))
		.SelectedRowKeys(new JS(@"component.option(""value"") ? [component.option(""value"")] : []"))
		.OnSelectionChanged(
			@<text>
				function(selectedItems) {
				var keys = selectedItems.selectedRowKeys;
				component.option("value", keys);
				component.close();
				}
			 </text>)
		)
}

Source/VrseWebApplication/Views/TestDevExtreme/Partials/DxPartialView01.cshtml
@model VrseWebApplication.Models.DxTestPartial01ViewModel

<script>
	function DxPartialView01Func1(a) {
		console.log(`DX Partial View 01: DxPartialView01Func1('${a}').`);
	}

	$(function() {
		console.log("DX Partial View 01: Document ready.");
		DxPartialView01Func1("dx-p1");
		DxView01Func1("dx-p1");
	});

	function sendForm_begin() {
		console.log("DX Partial View 01: sendForm_begin.");

		showLoadingPanel($('body'), 1);
		sleep(1000);
	}

	function sendForm_complete() {
		console.log("DX Partial View 01: sendForm_complete.");

		sleep(1000);
		hideLoadingPanel();
	}

	function sendForm_success(data) {
		console.log("DX Partial View 01: sendForm_success.");

		sleep(1000);
		hideLoadingPanel();

		if (data.error) {
			// Im Fehlerfall, Partial in meinem Container anzeigen.
			const cont = $('#partial-view-01-container');
			fillHtmlIntoContainer(data.html, cont);
		} else {
			// Erfolg, Partial in anderem Container anzeigen.
			const cont = $('#partial-view-02-container');
			fillHtmlIntoContainer(data.html, cont);
		}
	}
</script>

<h3>DX Partial View 01</h3>

<p>Content of the DX Partial View 01. Passed ID: <strong>@Model?.Id</strong>.</p>

@* https://dotnetthoughts.net/jquery-unobtrusive-ajax-helpers-in-aspnet-core/ *@
<form id="formPartial01"
      asp-antiforgery="true"
      asp-controller="TestDevExtreme"
      asp-action="DxPostPartialView01"
      data-ajax="true"
      data-ajax-method="post"
      data-ajax-begin="sendForm_begin"
      data-ajax-complete="sendForm_complete"
      data-ajax-success="sendForm_success"
      data-ajax-failure="sendForm_failure"
      autocomplete="off">
	
@using (Html.DevExtreme().ValidationGroup())
{
	@Html.ValidationSummary()

	<div class="form-panel">
		<div class="form-fields-area">
			<div class="row">
				<div class="col-12">
					@Html.LabelFor(m => m.Id, new { @class = @"form-label" })
				</div>
				<div class="col-12">
					@Html.DevExtreme().TextBoxFor(m => m.Id).ElementAttr(new {@class=@"form-control w-100"})
					@Html.ValidationMessageFor(m => m.Id)
				</div>
			</div>

			<div class="form-button-area">
				<hr/>
				<div class="row">
					<div class="col-12">
						<button type="submit" class="btn btn-primary">Send</button>
					</div>
				</div>
			</div>
		</div>
	</div>
}
</form>

<div id="partial-view-02-container" class="mt-3">
	Click <kbd>Send</kbd>.
</div>

Source/VrseWebApplication/Views/TestDevExtreme/Partials/DxPartialView04.cshtml
@model int

<script>
	function DxPartialView02Func1(a) {
		console.log(`DX Partial View 02: DxPartialView02Func1('${a}').`);
	}

	$(function() {
		console.log("DX Partial View 02: Document ready.");
		DxPartialView02Func1("dx-p2");
		DxView01Func1("dx-p2");
	});
</script>

<h3>DX Partial View 02</h3>

<p>Content of the DX Partial View 02. Passed ID: <strong>@Model</strong>.</p>